//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSPLinker {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSPLinker.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;items&quot;:[{&quot;itemId&quot;:1001,&quot;name&quot;:&quot;铁矿&quot;},{&quot;itemId&quot;:1002,&quot;name&quot;:&quot;铜矿&quot;},{&quot;itemId&quot;:1003,&quot;name&quot;:&quot;硅石&quot;},{&quot;itemId&quot;:1004,&quot;name&quot;:&quot;钛石&quot;},{&quot;itemId&quot;:1005,&quot;name&quot;:&quot;石矿&quot;},{&quot;itemId&quot;:1006,&quot;name&quot;:&quot;煤矿&quot;},{&quot;itemId&quot;:1030,&quot;name&quot;:&quot;木材&quot;},{&quot;itemId&quot;:1031,&quot;name&quot;:&quot;植物燃料&quot;},{&quot;itemId&quot;:1011,&quot;name&quot;:&quot;可燃冰&quot;},{&quot;itemId&quot;:1012,&quot;name&quot;:&quot;金伯利矿石&quot;},{&quot;itemId&quot;:1013,&quot;name&quot;:&quot;分形硅石&quot;},{&quot;itemId&quot;:1014,&quot;name&quot;:&quot;光栅石&quot;},{&quot;itemId&quot;:1015,&quot;name&quot;:&quot;刺笋结晶&quot;},{&quot;itemId&quot;:1016,&quot;name&quot;:&quot;单极磁石&quot;},{&quot;itemId&quot;:1101,&quot;name&quot;:&quot;铁块&quot;},{&quot;itemId&quot;:1104,&quot;name&quot;:&quot;铜块&quot;},{&quot;itemId&quot;:1105,&quot;name&quot;:&quot;高纯硅块&quot;},... 的本地化字符串。
        /// </summary>
        internal static string ldb {
            get {
                return ResourceManager.GetString("ldb", resourceCulture);
            }
        }
    }
}
